output "cluster_id" {
  description = "EKS cluster ID."
  value       = aws_eks_cluster.eks_cluster.id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = aws_eks_cluster.eks_cluster.endpoint
}

output "kubectl_certificate_authority" {
  description = "kubectl config as generated by the module."
  value       = aws_eks_cluster.eks_cluster.certificate_authority[0].data
}


output "kubeconfig_token" {
  description = "Admin user token"
  value       = data.aws_eks_cluster_auth.cluster_auth.token
  sensitive = true
}


